# Generated by Django 6.0.2 on 2026-02-10 06:26

import uploads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[uploads.validators.validate_file_size, uploads.validators.validate_file_extension]),
        ),
    ]
