# Generated by Django 6.0.2 on 2026-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_uploadedfile_options_uploadedfile_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
